name = 'Fractured Worlds RPG'
type = 'rpg'
# will only be read by the client
shortName = 'Fractured Worlds'
description = 'The JRPG styled companion to the Fractured Worlds campaign.'
themeColor = '#9900ff'

modules = [
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/title-screen',
    '@rpgjs/save',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad',
    './main', # add after '@rpgjs/mobile-gui'
    './gui'
]


[vite]
    # base = "https://sethmaxson.github.io/fractured-worlds-rpg"

[vite.server]
    port = 62318

[compilerOptions.build]
  serverUrl = "$ENV:VITE_SERVER_URL"

[titleScreen]
    title = 'Fractured Worlds'
    # music = '<sound id>'

[canvas]
    antialias = false
    autoDensity = true
    #resolution = 1.1


[inputs.action]
    name = "action"
    bind = ["space", "enter"]
    # bind = ["space", "enter", "click"]


[start]
    # map = 'somewhere-district-1'
    map = 'vehicle-one-more-day'
    # map = 'wonderland-visit-1-maze'
    # map = 'npc-test'
    graphic = 'tero-2'
    hitbox = [16, 16]